version: '3'

services:
  filebrowser:
    image: filebrowser/filebrowser
    container_name: filebrowser
    restart: unless-stopped
    volumes:
      - /srv/share:/srv
      - ./filebrowser/filebrowser.db:/filebrowser.db
      - ./filebrowser/.filebrowser.json:/.filebrowser.json
      - ./custom.css:/custom.css
    user: "1000:1000"

networks:
  default:
    name: nginx
    external: true
